name: 'Run Node.JS Tests'
author: 'Sky'
description: 'Test node code'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env: 
    a: 'b'
  args:
    - ${{ inputs.root-dir }}
branding:
  icon: 'check'
  color: 'purple'