name: 'Run tests.'
author: 'Kuanwen Lai'
description: 'This action let you run tests whitch is saved and managed on other repository.'
inputs:
  tests-repo-ssh-key: 
    description: 'ssh key to access repository whitch you save your tests.'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env: 
    a: 'b'
  args:
    - ${{ inputs.tests-repo-ssh-key }}
branding:
  icon: 'check'
  color: 'purple'